python tools/analysis_tools/confusion_matrixBenz.py configs/atss/atss_r101_InfectNucAug.py work_dirs/atss_r101_InfectNucAug/test_result.pkl work_dirs/atss_r101_InfectNucAug
python tools/analysis_tools/confusion_matrixBenz.py configs/atss/atss_r101_InfectNucNo.py work_dirs/atss_r101_InfectNucNo/test_result.pkl work_dirs/atss_r101_InfectNucNo
python tools/analysis_tools/confusion_matrixBenz.py configs/atss/atss_r50_InfectNucAug.py work_dirs/atss_r50_InfectNucAug/test_result.pkl work_dirs/atss_r50_InfectNucAug
python tools/analysis_tools/confusion_matrixBenz.py configs/atss/atss_r50_InfectNucNo.py work_dirs/atss_r50_InfectNucNo/test_result.pkl work_dirs/atss_r50_InfectNucNo
# python tools/analysis_tools/confusion_matrixBenz.py configs/dcn/DCN_r101_InfectNucAug.py work_dirs/DCN_r101_InfectNucAug/test_result.pkl work_dirs/DCN_r101_InfectNucAug
# python tools/analysis_tools/confusion_matrixBenz.py configs/dcn/DCN_r101_InfectNucNo.py work_dirs/DCN_r101_InfectNucNo/test_result.pkl work_dirs/DCN_r101_InfectNucNo
# python tools/analysis_tools/confusion_matrixBenz.py configs/dcn/DCN_r50_InfectNucAug.py work_dirs/DCN_r50_InfectNucAug/test_result.pkl work_dirs/DCN_r50_InfectNucAug
# python tools/analysis_tools/confusion_matrixBenz.py configs/dcn/DCN_r50_InfectNucNo.py work_dirs/DCN_r50_InfectNucNo/test_result.pkl work_dirs/DCN_r50_InfectNucNo
# python tools/analysis_tools/confusion_matrixBenz.py configs/deformable_detr/deformable_detr_r50_InfectNucAug.py work_dirs/deformable_detr_r50_InfectNucAug/test_result.pkl work_dirs/deformable_detr_r50_InfectNucAug
# python tools/analysis_tools/confusion_matrixBenz.py configs/deformable_detr/deformable_detr_r50_InfectNucNo.py work_dirs/deformable_detr_r50_InfectNucNo/test_result.pkl work_dirs/deformable_detr_r50_InfectNucNo
# python tools/analysis_tools/confusion_matrixBenz.py configs/faster_rcnn/faster_rcnn_r101_InfectNucAug.py work_dirs/faster_rcnn_r101_InfectNucAug/test_result.pkl work_dirs/faster_rcnn_r101_InfectNucAug
# python tools/analysis_tools/confusion_matrixBenz.py configs/faster_rcnn/faster_rcnn_r101_InfectNucNo.py work_dirs/faster_rcnn_r101_InfectNucNo/test_result.pkl work_dirs/faster_rcnn_r101_InfectNucNo
# python tools/analysis_tools/confusion_matrixBenz.py configs/faster_rcnn/faster_rcnn_r50_InfectNucAug.py work_dirs/faster_rcnn_r50_InfectNucAug/test_result.pkl work_dirs/faster_rcnn_r50_InfectNucAug
# python tools/analysis_tools/confusion_matrixBenz.py configs/faster_rcnn/faster_rcnn_r50_InfectNucNo.py work_dirs/faster_rcnn_r50_InfectNucNo/test_result.pkl work_dirs/faster_rcnn_r50_InfectNucNo
# python tools/analysis_tools/confusion_matrixBenz.py configs/mask_rcnn/mask_rcnn_r101_InfectNucAug.py work_dirs/mask_rcnn_r101_InfectNucAug/test_result.pkl work_dirs/mask_rcnn_r101_InfectNucAug
# python tools/analysis_tools/confusion_matrixBenz.py configs/mask_rcnn/mask_rcnn_r101_InfectNucNo.py work_dirs/mask_rcnn_r101_InfectNucNo/test_result.pkl work_dirs/mask_rcnn_r101_InfectNucNo
# python tools/analysis_tools/confusion_matrixBenz.py configs/mask_rcnn/mask_rcnn_r50_InfectNucAug.py work_dirs/mask_rcnn_r50_InfectNucAug/test_result.pkl work_dirs/mask_rcnn_r50_InfectNucAug
# python tools/analysis_tools/confusion_matrixBenz.py configs/mask_rcnn/mask_rcnn_r50_InfectNucNo.py work_dirs/mask_rcnn_r50_InfectNucNo/test_result.pkl work_dirs/mask_rcnn_r50_InfectNucNo