python tools/analysis_tools/get_flopsBenz.py configs/atss/atss_r101_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/atss/atss_r101_CellNucNo.py
python tools/analysis_tools/get_flopsBenz.py configs/atss/atss_r50_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/atss/atss_r50_CellNucNo.py
python tools/analysis_tools/get_flopsBenz.py configs/dcn/DCN_r101_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/dcn/DCN_r101_CellNucNo.py
python tools/analysis_tools/get_flopsBenz.py configs/dcn/DCN_r50_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/dcn/DCN_r50_CellNucNo.py
python tools/analysis_tools/get_flopsBenz.py configs/deformable_detr/deformable_detr_r50_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/deformable_detr/deformable_detr_r50_CellNucNo.py
python tools/analysis_tools/get_flopsBenz.py configs/faster_rcnn/faster_rcnn_r101_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/faster_rcnn/faster_rcnn_r101_CellNucNo.py
python tools/analysis_tools/get_flopsBenz.py configs/faster_rcnn/faster_rcnn_r50_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/faster_rcnn/faster_rcnn_r50_CellNucNo.py
python tools/analysis_tools/get_flopsBenz.py configs/mask_rcnn/mask_rcnn_r101_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/mask_rcnn/mask_rcnn_r101_CellNucNo.py
python tools/analysis_tools/get_flopsBenz.py configs/mask_rcnn/mask_rcnn_r50_CellNucAug.py
python tools/analysis_tools/get_flopsBenz.py configs/mask_rcnn/mask_rcnn_r50_CellNucNo.py