_base_ = [
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
model = dict(
    type='GFL',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_output',
        num_outs=5),
    bbox_head=dict(
        type='GFLHead',
        num_classes=214,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            ratios=[1.0],
            octave_base_scale=8,
            scales_per_octave=1,
            strides=[8, 16, 32, 64, 128]),
        loss_cls=dict(
            type='QualityFocalLoss',
            use_sigmoid=True,
            beta=2.0,
            loss_weight=1.0),
        loss_dfl=dict(type='DistributionFocalLoss', loss_weight=0.25),
        reg_max=16,
        loss_bbox=dict(type='GIoULoss', loss_weight=2.0)),
    # training and testing settings
    train_cfg=dict(
        assigner=dict(type='ATSSAssigner', topk=9),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.6),
        max_per_img=100))
# optimizer
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)

# 1. dataset settings
dataset_type = 'CocoDataset'
data_root = '/workspace/fast_data_2/data_zha/card_detection/sdr_human_prototype/'
classes = (
                "big",
                "old",
                "short",
                "small",
                "strong",
                "tall",
                "weak",
                "young",
                "bird",
                "butterfly",
                "cat",
                "chicken",
                "cow",
                "crab",
                "crocodile",
                "deer",
                "dog",
                "duck",
                "elephant",
                "fish",
                "frog",
                "horse",
                "lion",
                "monkey",
                "pig",
                "shell",
                "snake",
                "tiger",
                "comb",
                "shampoo",
                "shower",
                "soap",
                "tissue",
                "toilet",
                "toothbrush",
                "toothpaste",
                "towel",
                "alarmclock",
                "bed",
                "blanket",
                "curtain",
                "dresser",
                "lamp",
                "mirror",
                "pajamas",
                "pillow",
                "wardrobe",
                "arm",
                "chin",
                "ear",
                "elbow",
                "eye",
                "eyebrow",
                "foot",
                "hand",
                "knee",
                "mouth",
                "neck",
                "nose",
                "shoulder",
                "teeth",
                "tongue",
                "black",
                "blue",
                "brown",
                "gray",
                "green",
                "pink",
                "red",
                "white",
                "yellow",
                "belt",
                "cap",
                "ring",
                "shirt",
                "shoes",
                "shorts",
                "skirt",
                "socks",
                "umbrella",
                "watch",
                "friday",
                "monday",
                "saturday",
                "sunday",
                "thursday",
                "tuesday",
                "wednesday",
                "bread",
                "cake",
                "cookies",
                "doughnut",
                "eggs",
                "icecream",
                "milk",
                "noodles",
                "popcorn",
                "rice",
                "tofu",
                "water",
                "apple",
                "banana",
                "grape",
                "mango",
                "mangosteen",
                "orange",
                "papaya",
                "pineapple",
                "rambutan",
                "roseapple",
                "watermelon",
                "broom",
                "bucket",
                "chair",
                "clock",
                "door",
                "fan",
                "mop",
                "radio",
                "refrigerator",
                "table",
                "telephone",
                "television",
                "window",
                "blender",
                "bowl",
                "fork",
                "glass",
                "knife",
                "pan",
                "pitcher",
                "plate",
                "spoon",
                "april",
                "august",
                "december",
                "february",
                "january",
                "july",
                "june",
                "march",
                "may",
                "november",
                "october",
                "september",
                "cloud",
                "flower",
                "moon",
                "mountain",
                "rain",
                "rainbow",
                "river",
                "rock",
                "sand",
                "thunder",
                "eight",
                "five",
                "four",
                "nine",
                "one",
                "seven",
                "six",
                "ten",
                "three",
                "two",
                "chef",
                "doctor",
                "farmer",
                "merchant",
                "monk",
                "nurse",
                "policeman",
                "soldier",
                "teacher",
                "worker",
                "circle",
                "heptagon",
                "hexagon",
                "octagon",
                "oval",
                "pentagon",
                "rectangle",
                "triangle",
                "backpack",
                "book",
                "eraser",
                "glue",
                "notebook",
                "pen",
                "pencil",
                "ruler",
                "scissors",
                "airplane",
                "bicycle",
                "boat",
                "bus",
                "car",
                "helicopter",
                "motorcycle",
                "train",
                "truck",
                "tuktuk",
                "brushmyteeth",
                "dress",
                "drink",
                "eat",
                "rubbodydry",
                "sleep",
                "takeabath",
                "takeapee",
                "takeapoo",
                "washmyhair",
                "washmyhand",
                "person"
            )

data = dict(
    samples_per_gpu=32,
    workers_per_gpu=8,
    train=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file=data_root + 'instances_train.json',
        img_prefix=data_root + 'RGBfd222655-7872-41fd-900c-89a31f829232/',
        ),
    val=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='/workspace/fast_data_2/data_zha/card_detection/cardBox/robot_card_test_coco-human.json',
        img_prefix='/workspace/fast_data_2/data_zha/card_detection/cardBox/',
        ),
    test=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='/workspace/fast_data_2/data_zha/card_detection/cardBox/robot_card_test_coco-human.json',
        img_prefix='/workspace/fast_data_2/data_zha/card_detection/cardBox/',
        ),
    )

fp16 = dict(loss_scale=512.)
    
load_from = 'pretrained_models/gfl_r50_fpn_1x_coco_20200629_121244-25944287.pth'
