_base_ = [
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

# model settings
model = dict(
    type='RPN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0)))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_label=False),
    dict(type='Resize', img_scale=(512, 512), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes']),
]

# optimizer
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)

# 1. dataset settings
dataset_type = 'CocoDataset'
data_root = '/workspace/fast_data_2/data_zha/card_detection/sdr_human_prototype/'
classes = (
                "big",
                "old",
                "short",
                "small",
                "strong",
                "tall",
                "weak",
                "young",
                "bird",
                "butterfly",
                "cat",
                "chicken",
                "cow",
                "crab",
                "crocodile",
                "deer",
                "dog",
                "duck",
                "elephant",
                "fish",
                "frog",
                "horse",
                "lion",
                "monkey",
                "pig",
                "shell",
                "snake",
                "tiger",
                "comb",
                "shampoo",
                "shower",
                "soap",
                "tissue",
                "toilet",
                "toothbrush",
                "toothpaste",
                "towel",
                "alarmclock",
                "bed",
                "blanket",
                "curtain",
                "dresser",
                "lamp",
                "mirror",
                "pajamas",
                "pillow",
                "wardrobe",
                "arm",
                "chin",
                "ear",
                "elbow",
                "eye",
                "eyebrow",
                "foot",
                "hand",
                "knee",
                "mouth",
                "neck",
                "nose",
                "shoulder",
                "teeth",
                "tongue",
                "black",
                "blue",
                "brown",
                "gray",
                "green",
                "pink",
                "red",
                "white",
                "yellow",
                "belt",
                "cap",
                "ring",
                "shirt",
                "shoes",
                "shorts",
                "skirt",
                "socks",
                "umbrella",
                "watch",
                "friday",
                "monday",
                "saturday",
                "sunday",
                "thursday",
                "tuesday",
                "wednesday",
                "bread",
                "cake",
                "cookies",
                "doughnut",
                "eggs",
                "icecream",
                "milk",
                "noodles",
                "popcorn",
                "rice",
                "tofu",
                "water",
                "apple",
                "banana",
                "grape",
                "mango",
                "mangosteen",
                "orange",
                "papaya",
                "pineapple",
                "rambutan",
                "roseapple",
                "watermelon",
                "broom",
                "bucket",
                "chair",
                "clock",
                "door",
                "fan",
                "mop",
                "radio",
                "refrigerator",
                "table",
                "telephone",
                "television",
                "window",
                "blender",
                "bowl",
                "fork",
                "glass",
                "knife",
                "pan",
                "pitcher",
                "plate",
                "spoon",
                "april",
                "august",
                "december",
                "february",
                "january",
                "july",
                "june",
                "march",
                "may",
                "november",
                "october",
                "september",
                "cloud",
                "flower",
                "moon",
                "mountain",
                "rain",
                "rainbow",
                "river",
                "rock",
                "sand",
                "thunder",
                "eight",
                "five",
                "four",
                "nine",
                "one",
                "seven",
                "six",
                "ten",
                "three",
                "two",
                "chef",
                "doctor",
                "farmer",
                "merchant",
                "monk",
                "nurse",
                "policeman",
                "soldier",
                "teacher",
                "worker",
                "circle",
                "heptagon",
                "hexagon",
                "octagon",
                "oval",
                "pentagon",
                "rectangle",
                "triangle",
                "backpack",
                "book",
                "eraser",
                "glue",
                "notebook",
                "pen",
                "pencil",
                "ruler",
                "scissors",
                "airplane",
                "bicycle",
                "boat",
                "bus",
                "car",
                "helicopter",
                "motorcycle",
                "train",
                "truck",
                "tuktuk",
                "brushmyteeth",
                "dress",
                "drink",
                "eat",
                "rubbodydry",
                "sleep",
                "takeabath",
                "takeapee",
                "takeapoo",
                "washmyhair",
                "washmyhand",
                "person"
            )

data = dict(
    samples_per_gpu=32,
    workers_per_gpu=8,
    train=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file=data_root + 'instances_train.json',
        img_prefix=data_root + 'RGBfd222655-7872-41fd-900c-89a31f829232/',
        pipeline=train_pipeline
        ),
    val=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='/workspace/fast_data_2/data_zha/card_detection/cardBox/robot_card_test_coco-human.json',
        img_prefix='/workspace/fast_data_2/data_zha/card_detection/cardBox/',
        ),
    test=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='/workspace/fast_data_2/data_zha/card_detection/cardBox/robot_card_test_coco-human.json',
        img_prefix='/workspace/fast_data_2/data_zha/card_detection/cardBox/',
        ),
    )

fp16 = dict(loss_scale=512.)

evaluation = dict(interval=1, metric='proposal_fast')

load_from = 'pretrained_models/rpn_r50_fpn_1x_coco_20200218-5525fa2e.pth'


